-- Adopt @geiger/rbac for Forms
--
-- Storage for the suite authorization engine: public.roles (shared role
-- definitions, suite-wide) + forms.role_grants (this product's assignments) +
-- forms.rbac_allows() (the predicate RLS policies call).
--
-- Generated by @geiger/rbac migrationSql("forms") — do not hand-edit the
-- storage block; regenerate from the package if the format changes.
--
-- NOTE ON ENFORCEMENT. This migration only creates the authorization tables.
-- It does NOT replace any forms table's demo-open policy — flipping those is
-- a separate, deliberate migration per table, because a missing grant becomes
-- a blank screen rather than a hidden button the moment it lands.
-- System roles (owner/admin/manager/member/viewer) are seeded by the app via
-- ensureSystemRoles() from geiger-rbac.config.js, matching geiger-events.
--
-- Fresh product: no backfill from a pre-package overlay (Forms has none).

-- @up
create extension if not exists pgcrypto;
create schema if not exists forms;
grant usage on schema forms to anon, authenticated, service_role;

-- Shared updated_at trigger for the authorization tables. Declared here (rather
-- than depending on a product's own touch_updated_at) so this block stands alone
-- whichever product runs it first.
create or replace function public.rbac_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Wildcard permission matching. Mirrors keys.js: "*" matches everything,
-- "<product>.*" and "<product>.<resource>.*" match by prefix, anything else is
-- an exact match. Immutable so it can be used in an index if that day comes.
create or replace function public.rbac_key_matches(p_patterns text[], p_key text)
returns boolean
language sql
immutable
as $$
  select exists (
    select 1
    from unnest(coalesce(p_patterns, '{}'::text[])) as pat
    where pat = '*'
       or pat = p_key
       or (
         right(pat, 2) = '.*'
         and left(p_key, length(pat) - 1) = left(pat, length(pat) - 1)
       )
  );
$$;

-- Shared role definitions. project_id scopes a role to one workspace; a null
-- project_id is a suite-wide template. permissions[] holds keys and wildcard
-- patterns spanning every product (forms.form.edit, events.order.refund, "*").
create table if not exists public.roles (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade,
  key text,
  name text not null default 'Untitled role',
  description text not null default '',
  color text not null default 'slate',
  permissions text[] not null default '{}',
  is_system boolean not null default false,
  sort integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table public.roles add column if not exists key text;
alter table public.roles add column if not exists permissions text[] not null default '{}';
alter table public.roles add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table public.roles add column if not exists deleted_at timestamptz;

create index if not exists roles_project_idx
  on public.roles (project_id) where deleted_at is null;
create unique index if not exists roles_project_key_uniq
  on public.roles (project_id, key) where key is not null and deleted_at is null;

drop trigger if exists roles_touch_updated_at on public.roles;
create trigger roles_touch_updated_at
before update on public.roles
for each row execute function public.rbac_touch_updated_at();

-- Per-product assignment. One row per (user, role) in a project. scope narrows
-- the grant to specific resources: {"form": ["<uuid>", ...]}. An empty scope
-- means the grant applies everywhere in the project.
create table if not exists forms.role_grants (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade,
  user_id uuid not null,
  role_id uuid not null references public.roles(id) on delete cascade,
  scope jsonb not null default '{}'::jsonb,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  granted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

alter table forms.role_grants add column if not exists scope jsonb not null default '{}'::jsonb;
alter table forms.role_grants add column if not exists metadata jsonb not null default '{}'::jsonb;
alter table forms.role_grants add column if not exists deleted_at timestamptz;

-- The lookup rbac_allows() makes on every row of every gated query.
create index if not exists forms_role_grants_lookup_idx
  on forms.role_grants (user_id, project_id) where deleted_at is null;
create index if not exists forms_role_grants_role_idx
  on forms.role_grants (role_id) where deleted_at is null;
create unique index if not exists forms_role_grants_uniq
  on forms.role_grants (project_id, user_id, role_id) where deleted_at is null;

drop trigger if exists role_grants_touch_updated_at on forms.role_grants;
create trigger role_grants_touch_updated_at
before update on forms.role_grants
for each row execute function public.rbac_touch_updated_at();

-- The predicate every gated policy calls.
--
-- SECURITY DEFINER so a user can be authorized by grant rows they cannot
-- themselves select — otherwise the grants table's own RLS would have to be
-- open for authorization to work at all. STABLE so Postgres may cache it within
-- a statement rather than re-running it per row.
create or replace function forms.rbac_allows(
  p_permission text,
  p_project uuid default null,
  p_scope_type text default null,
  p_scope_id uuid default null
)
returns boolean
language sql
stable
security definer
set search_path = public, forms
as $$
  select exists (
    select 1
    from forms.role_grants g
    join public.roles r on r.id = g.role_id
    where g.user_id = auth.uid()
      and g.status = 'active'
      and g.deleted_at is null
      and r.deleted_at is null
      and (p_project is null or g.project_id = p_project)
      and public.rbac_key_matches(r.permissions, p_permission)
      and (
        p_scope_type is null
        or not jsonb_exists(g.scope, p_scope_type)
        or (
          p_scope_id is not null
          and jsonb_exists(g.scope -> p_scope_type, p_scope_id::text)
        )
      )
  );
$$;

grant execute on function forms.rbac_allows(text, uuid, text, uuid) to anon, authenticated;
grant execute on function public.rbac_key_matches(text[], text) to anon, authenticated;

alter table public.roles enable row level security;
alter table forms.role_grants enable row level security;

drop policy if exists roles_read on public.roles;
create policy roles_read on public.roles
  for select to anon, authenticated using (deleted_at is null);

drop policy if exists roles_write on public.roles;
create policy roles_write on public.roles
  for all to authenticated using (true) with check (true);

drop policy if exists role_grants_read on forms.role_grants;
create policy role_grants_read on forms.role_grants
  for select to anon, authenticated using (deleted_at is null);

drop policy if exists role_grants_write on forms.role_grants;
create policy role_grants_write on forms.role_grants
  for all to authenticated using (true) with check (true);

-- @down
drop policy if exists role_grants_read on forms.role_grants;
drop policy if exists role_grants_write on forms.role_grants;
drop function if exists forms.rbac_allows(text, uuid, text, uuid);
drop table if exists forms.role_grants cascade;

-- public.roles, public.rbac_key_matches and public.rbac_touch_updated_at are
-- shared across the suite and are intentionally left in place — dropping them
-- would delete another product's role definitions.
